[flags]
enable_gpu = true

[processes]
columns = ["name", "cpu%", "mem%", "gmem%", "gpu%"]

[[row]]
[[row.child]]
type = "proc"

[[row]]
[[row.child]]
type = "cpu"
ratio = 7
[[row.child]]
ratio = 2
type = "temp"
