[manager]
prepend_keymap = [
  { on = "p", run = "plugin --sync smart-paste", desc = "Paste into the hovered directory or CWD" },
  { on = "<C-t>", run = "tab_create --current", desc = "Create a new tab with CWD" },
  { on = "<C-1>", run = "tab_switch 0", desc = "Switch to the first tab" },
  { on = "<C-2>", run = "tab_switch 1", desc = "Switch to the second tab" },
  { on = "<C-3>", run = "tab_switch 2", desc = "Switch to the third tab" },
  { on = "<C-4>", run = "tab_switch 3", desc = "Switch to the fourth tab" },
  { on = "<C-5>", run = "tab_switch 4", desc = "Switch to the fifth tab" },
  { on = "<C-6>", run = "tab_switch 5", desc = "Switch to the sixth tab" },
  { on = "<C-7>", run = "tab_switch 6", desc = "Switch to the seventh tab" },
  { on = "<C-8>", run = "tab_switch 7", desc = "Switch to the eighth tab" },
  { on = "<C-9>", run = "tab_switch 8", desc = "Switch to the ninth tab" },
  { on = "<C-.>", run = "hidden toggle", desc = "Toggle the visibility of hidden files" },
  { on = "?", run = "help", desc = "Open help" },
  { on = "<C-w>", run = "close", desc = "Close the current tab" },
  { on = "<Enter>", run = "plugin --sync smart-enter", desc = "Enter the child directory, or open the file" },
  { on = "w", run = "enter", desc = "Enter the selected directory" },
  { on = "O", run = "open --interactive", desc = "Open selected files interactively" },
  { on = "b", run = "leave", desc = "Go back to the parent directory" },
  { on = "<Space>", run = "plugin --sync max-preview", desc = "Maximize or restore preview" },
]
