import = ["~/.config/alacritty/themes/tokyo-night.toml"]

working_directory = "/Users/magnusrodseth/dev"

[shell]
program = "/bin/zsh"
# Immediately start tmux
args = ["-l", "-c", "tmux attach || tmux"]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 400, lines = 500 }
startup_mode = "Maximized"
padding = { x = 10, y = 35 }
decorations = "Transparent"

[font]
normal.family = "FiraCode Nerd Font Mono"
size = 16
offset.y = 1

[cursor]
style.shape = "Block"

[keyboard]
bindings = [
  # CMD + t: New tab (new tmux window)
  { key = "T", mods = "Command", command = { program = "/usr/local/bin/tmux", args = [
    "new-window",
    "/usr/local/bin/zsh",
  ] } },
  # CMD + w: Close pane (close tmux pane)
  { key = "W", mods = "Command", command = { program = "/usr/local/bin/tmux", args = [
    "kill-pane",
  ] } },
  # CMD + d: Split pane horizontally
  { key = "D", mods = "Command", command = { program = "/usr/local/bin/tmux", args = [
    "split-window",
    "-h",
    "-c",
    "#{pane_current_path}",
  ] } },
  # CMD + shift + d: Split pane vertically
  { key = "D", mods = "Command|Shift", command = { program = "/usr/local/bin/tmux", args = [
    "split-window",
    "-c",
    "#{pane_current_path}",
  ] } },
  # CMD + number: Switch to window
  { key = "Key1", mods = "Command", command = { program = "/usr/local/bin/tmux", args = [
    "select-window",
    "-t",
    "1",
  ] } },
  { key = "Key2", mods = "Command", command = { program = "/usr/local/bin/tmux", args = [
    "select-window",
    "-t",
    "2",
  ] } },
  { key = "Key3", mods = "Command", command = { program = "/usr/local/bin/tmux", args = [
    "select-window",
    "-t",
    "3",
  ] } },
  { key = "Key4", mods = "Command", command = { program = "/usr/local/bin/tmux", args = [
    "select-window",
    "-t",
    "4",
  ] } },
  { key = "Key5", mods = "Command", command = { program = "/usr/local/bin/tmux", args = [
    "select-window",
    "-t",
    "5",
  ] } },
  { key = "Key6", mods = "Command", command = { program = "/usr/local/bin/tmux", args = [
    "select-window",
    "-t",
    "6",
  ] } },
  { key = "Key7", mods = "Command", command = { program = "/usr/local/bin/tmux", args = [
    "select-window",
    "-t",
    "7",
  ] } },
  { key = "Key8", mods = "Command", command = { program = "/usr/local/bin/tmux", args = [
    "select-window",
    "-t",
    "8",
  ] } },
  { key = "Key9", mods = "Command", command = { program = "/usr/local/bin/tmux", args = [
    "select-window",
    "-t",
    "9",
  ] } },
  # CMD + arrows: Navigate tmux panes
  { key = "Left", mods = "Command", command = { program = "/usr/local/bin/tmux", args = [
    "select-pane",
    "-L",
  ] } },
  { key = "Right", mods = "Command", command = { program = "/usr/local/bin/tmux", args = [
    "select-pane",
    "-R",
  ] } },
  { key = "Up", mods = "Command", command = { program = "/usr/local/bin/tmux", args = [
    "select-pane",
    "-U",
  ] } },
  { key = "Down", mods = "Command", command = { program = "/usr/local/bin/tmux", args = [
    "select-pane",
    "-D",
  ] } },

  # CMD + K: Clear terminal screen in tmux using the `clear` command
  { key = "K", mods = "Command", command = { program = "/usr/local/bin/tmux", args = [
    "send-keys",
    "clear",
    "Enter",
  ] } },

  # CMD + Shift + Enter: Full size the active tmux pane
  { key = "Enter", mods = "Command|Shift", command = { program = "/usr/local/bin/tmux", args = [
    "resize-pane",
    "-Z",
  ] } },
]

[mouse]
bindings = [{ mouse = "Right", action = "ReceiveChar" }]
